title: Medanarsitek.com Blog
markdown: kramdown
url: "https://medanarsitek.com/"
baseurl: "/

# for atom feed
author:
  name: Adm MedanArsitek
  email: lumbasawi@gmail.com
  image: "https://avatars1.githubusercontent.com/u/36638057?s=460&u=b7ea83b7f3172f4517c653cefd5d0713853561b2&v=4"
  bio: Developed by <b>:heart:</b> is Amazing Person.
  github: "/"

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:categories/:year/:month/:day/:title/
